repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        args: ['-h','--profile=black']
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: flake8
        args: ['--ignore=F405 E501 F403 W503']
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint .
        language: system
        types: [ python ]
        args: ['--disable=R0903','--disable=F0010',
               '--disable=E0401', '--disable=E1123',
               '--disable=C0103']
