name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Install pre-commit hooks
        run: poetry run pre-commit install
      - name: Run pytest
        run: poetry run pytest
