name: Run Docker image

on:
    workflow_call:

jobs:
  deploy:
    name: Power BI Refresh
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Pull Docker Image
        run: docker pull europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-powerbi:main
  
      - name: Run Docker Image
        env:
          POWERBI_CLIENT_SECRET: ${{ secrets.POWERBI_CLIENT_SECRET }}
        run: docker run --name testproject 
          -e "POWERBI_CLIENT_ID=${{ vars.POWERBI_CLIENT_ID }}" 
          -e "POWERBI_DATASET_ID=${{ vars.POWERBI_DATASET_ID }}" 
          -e "POWERBI_GROUP_ID=${{ vars.POWERBI_GROUP_ID }}" 
          -e "POWERBI_TENANT_ID=${{ vars.POWERBI_TENANT_ID }}" 
          -e "POWERBI_CLIENT_SECRET=$POWERBI_CLIENT_SECRET" 
          europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-powerbi:main