name: Build and Push Docker image

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-python:main  # TODO

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Pull Docker Image
        run: docker pull europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-python:main
  
      - name: Run Docker Image
        run: docker run \
          -e KEYFILE_PROJECT_ID=${{ env.KEYFILE_PROJECT_ID }} \
          -e KEYFILE_CLIENT_EMAIL=${{ env.KEYFILE_CLIENT_EMAIL }} \
          -e KEYFILE_CLIENT_ID=${{ env.KEYFILE_CLIENT_ID }} \
          -e KEYFILE_CLIENT_X509_CERT_URL=${{ env.KEYFILE_CLIENT_X509_CERT_URL }} \
          -e KEYFILE_PRIVATE_KEY_ID=${{ env.KEYFILE_PRIVATE_KEY_ID }} \
          -e KEYFILE_PRIVATE_KEY=${{ secrets.KEYFILE_PRIVATE_KEY }} \
          europe-west1-docker.pkg.dev/plateforme-data-demo/effidic-registry/plateforme-data-demo-python:main
